name: kungfubrotha
favicon: null
layout_spectrum: 0.33674737671390176
typography_spectrum: 0.8035283696372062
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.699456098023802
  lightness: 0.2618698589503765
  saturation: 0.4575368647929281
  rhythmicContrast: 0.42430456378497183
purpose: []
